### PR TITLE
recently selected stations

### PR DESCRIPTION
**Pull request by ThHanika**
include icon in favourites

### CODE REVIEW

**Comment by ThHanika** [comment]
this is an addition to allow favicons. The file with recently used stations is saved in directory .ycast . It is in compatible format to stations.yml so you can easily selected your favorites and expand your favorite-list

**Comment by Essoloani** [comment]
I'm using jonnieZG's Fork which is the best for my use.
It would be great to combine the two to come up with something new and easy to use. Since the master project seems abandoned.
It's just my wish.
Thanks!

**Comment by ThHanika** [comment]
> I'm using jonnieZG's Fork which is the best for my use. It would be great to combine the two to come up with something new and easy to use. Since the master project seems abandoned. It's just my wish. Thanks!

Sorry, but jonnieZG's Fork is buggy in radiobrowser.py, if you want the station-icon, always you get an error to get the station-info by_id. ( id_registry[tid] empty ). You never get the station-icon.

I am correct the issues, now you can install:
pip3 install git+https://github.com/ThHanika/YCast

remark, the stations are filtered by favicon exists

**Comment by Essoloani** [comment]
I installed your version and it works fine too.
When the device restarts, the icon of the last station listened to is not displayed.
When moving from a station with an icon to another without, the last icon remains displayed.
I didn't notice anything new while browsing radiobrowser.
Thanks!
 .ycast; must I create it?

**Comment by ThHanika** [comment]
> 

OK I get the same issue: Reason the station_list_cache  with the shorted number is cleared, so it misses the mapping from short number and stationuuid from radiobrowser. It is new created on selecting directory selection: countries, genre, languages.

I will try the solution: 
https://github.com/yay6/YCast/commit/145b902c37abf3abb2490b87e7798ffebfb24df2

I also developed an global filter, filter.yml, it reduces the choices on your interests 

> .ycast; must I create it?

no, the ycast service created it in the home-directory of the configured user for ycast-service (check user properties)

**Comment by Essoloani** [comment]
> When the device restarts, the icon of the last station listened to is not displayed.

Not fixed by the current version.
> When moving from a station with an icon to another without, the last icon remains displayed.

Fixed by the current version.

**Pull request closed without merging**
