### PR TITLE
Manage token request

### PR DESCRIPTION
**Pull request by Nimn**
I do not know if it is specific to my power amp (Yamaha R-N500) or if it is due to new Yamaha firmware but a token request is made at initialization.
 
This request is now managed with an arbitrary token reply.

This patch makes the server functional for me and should not break any functional installations.

### CODE REVIEW

**Comment by milaq** [comment]
Hey mate,
thanks for the PR.

Is it important which token content is returned? Does it have to be all 'a' and of that length?

Asking because I'd rather make it unique and distinguishable. Something like 'DEADBEEF' or 'ycast' (just for cosmetics).

**Comment by Nimn** [comment]
I have kept the length of the returned token by vtunner and kept it in hexadecimal but I'm not sure it matters. I'll do test tomorrow to see if the amp accepts 'ycast' or 'deadbeef'.

**Comment by milaq** [comment]
Hey again,

I've rebased and merged your commit here: https://github.com/milaq/YCast/commit/a1e6fdb8f882631715efe66567f54cb4da6009cd

Actually, I just tested it with my RX-V473 after depowering (I was using "network standby" before) and it also threw me an "access error".
I didn't encounter this one before; it seems like the AVR caches the token as long as it is plugged into the wall socket.

It doesn't seem to matter what access token gets replied. I just used "stub" for now.
Can you verify the latest master branch with your model (including pulling the plug for 5 seconds or so) and reply here? I'll keep this PR open until then for reference.

Thanks for your work :+1: and good night

**Comment by Nimn** [comment]
Just tested "stub" is ok with my model. Thanks for this software.

**Pull request closed without merging**
